# Generated by Django 2.0.7 on 2018-07-03 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='cover',
            field=models.FileField(null=True, upload_to='organisation/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
