# Generated by Django 2.0.7 on 2018-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
