# Generated by Django 2.0.7 on 2018-08-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20180825_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
