# Generated by Django 2.0.7 on 2018-07-23 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponser', '0001_initial'),
        ('event', '0002_event_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='sponser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sponser.Sponser'),
        ),
    ]
