# Generated by Django 2.0.7 on 2018-07-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='user',
            new_name='attendees',
        ),
    ]
