# Generated by Django 2.0.7 on 2018-07-04 04:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover',
            field=models.FileField(null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
