# Generated by Django 2.0.8 on 2018-08-10 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180724_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlocation',
            name='logo',
            field=models.FileField(null=True, upload_to='location/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='eventsponser',
            name='logo',
            field=models.FileField(null=True, upload_to='sponser/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
