# Generated by Django 2.0.8 on 2018-08-10 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180810_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover',
            field=models.FileField(null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
