# Generated by Django 2.0.7 on 2018-07-03 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180703_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='logo',
            field=models.FileField(blank=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
