# Generated by Django 2.0.7 on 2018-07-03 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20180703_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.FileField(null=True, upload_to='events/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])]),
        ),
    ]
