# Generated by Django 2.0.8 on 2018-08-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180811_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event',
            new_name='comment',
        ),
    ]
