# Generated by Django 2.0.7 on 2018-08-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20180811_1043'),
        ('event', '0006_auto_20180811_1024'),
    ]

    operations = [
    ]
