# Generated by Django 2.0.8 on 2018-09-01 14:41

from django.db import migrations, models
import django.db.models.deletion
import event_manager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20180813_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', event_manager.fields.JSONSchemaField(blank=True, default=list)),
                ('event', models.ManyToManyField(blank=True, null=True, to='event.Event')),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.FormType'),
        ),
    ]
