# Generated by Django 2.0.8 on 2018-09-06 02:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0013_auto_20180901_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserForm',
            new_name='Submission',
        ),
    ]
