# Generated by Django 2.0.9 on 2018-12-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20180906_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='latitute',
            field=models.DecimalField(decimal_places=6, default=24.926294, max_digits=9),
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='longitute',
            field=models.DecimalField(decimal_places=6, default=67.022095, max_digits=9),
        ),
    ]
