# Generated by Django 2.0.7 on 2018-07-16 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
