# Generated by Django 2.0.7 on 2018-07-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180703_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(height_field='200', null=True, upload_to='user/', width_field='200'),
        ),
    ]
